version = 1
SPDX-PackageName = "loyalty-contact-migration-verifier"
SPDX-PackageSupplier = "SAP Emarsys <support@emarsys.com>"
SPDX-PackageDownloadLocation = "https://github.com/emartech/loyalty-contact-migration-verifier"

[[annotations]]
path = ["README.md", "docs/**", "**.ini", "**.json", ".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP Emarsys"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ["**.sh", ".githooks/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP Emarsys"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = ["test_generators/test_files/**/**.csv", "test_generators/**.json", "test_generators/README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP Emarsys"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "**/.DS_Store"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP Emarsys"
SPDX-License-Identifier = "GPL-3.0-only"
